GalacticDynamics/galax

.pre-commit-config.yaml
pyproject.toml
src/galdynamix/__init__.py
src/galdynamix/dynamics/_core.py
src/galdynamix/dynamics/_orbit.py
src/galdynamix/dynamics/mockstream/_core.py
src/galdynamix/dynamics/mockstream/_df/base.py
src/galdynamix/dynamics/mockstream/_df/fardal.py
src/galdynamix/dynamics/mockstream/_mockstream_generator.py
src/galdynamix/integrate/_base.py
src/galdynamix/integrate/_builtin.py
src/galdynamix/potential/_potential/__init__.py
src/galdynamix/potential/_potential/base.py
src/galdynamix/potential/_potential/builtin.py
src/galdynamix/potential/_potential/composite.py
src/galdynamix/potential/_potential/core.py
src/galdynamix/potential/_potential/param/field.py
src/galdynamix/potential/_potential/subhalo.py
src/galdynamix/typing.py
src/galdynamix/units.py
src/galdynamix/utils/_collections.py
src/galdynamix/utils/_jax.py
src/galdynamix/utils/_shape.py
src/galdynamix/utils/dataclasses.py

Jaxtyping + Beartype + Checking whether the code can be run on broadcast arrays (runtime checks don't fail silently now).

Broadcasting code + correct shape annotations

---

src/galdynamix/potential/_potential/composite.py
src/galdynamix/potential/_potential/core.py
src/galdynamix/potential/_potential/utils.py

Using a `singledispatch` we can easily support any reasonable argument to the `units` field of a Potential. I built in `UnitSystem`, `None`, and the pre-defined unit-system names. But we could add Enums (for the pre-defined), a dictionary -> UnitSystem with full registration. Pretty much anything.

better units argument converter

---

src/galdynamix/units.py

Fix UnitSystem

---

src/galdynamix/dynamics/_core.py
src/galdynamix/dynamics/mockstream/_core.py
src/galdynamix/potential/_potential/param/core.py
src/galdynamix/utils/dataclasses.py

converter_float_array

---

src/galdynamix/potential/_potential/param/core.py
src/galdynamix/potential/_potential/param/field.py

Not perfect, it doesn't account for the expected output units, but it now checks for consistency.

Improve passing callable function as a parameter

---

src/galdynamix/potential/_potential/core.py
src/galdynamix/potential/_potential/param/field.py

Following #33. PyTrees inside JAX functions can be only partially constructed.

Fixup units check

---

src/galdynamix/potential/_potential/base.py

Pretty sure I got it correct. Need to add tests, but that's a larger issue library-wide. The AD makes this wonderfully simple.

tidal tensor

---

noxfile.py
pyproject.toml
src/galax/units.py
tests/unit/test_units.py

Note: This is built off of #44 
This adds some more meat to the UnitSystem port, and adds unit tests.

Some enhancements to the unit system stuff

---

pyproject.toml
src/galax/dynamics/_orbit.py
src/galax/dynamics/mockstream/_mockstream_generator.py
src/galax/integrate/_base.py
src/galax/integrate/_builtin.py
src/galax/potential/_potential/base.py

Instead of passing the integrator class and kwargs, you now pass an integrator instance. The integrators are equinox Modules (ie dataclasses) so the state is now reset by calling `replace` for each integration.

integrator instance, not class

---

src/galax/dynamics/mockstream/_core.py
src/galax/dynamics/mockstream/_mockstream_generator.py

Not arrays.
This is much closer to `gala`, which returns a single Mockstream for the whole stream (versus the 2 returned here).
Worth doing incrementally. I have this notion of some `CompositeMockstream` class that can hold the various pieces of a stream. Gala currently merges the arms into 1 object.
With `CompositeMockstream` e.g. if we do a sim with an ex-situ then in-situ stream from the same progenitor it would contain 4 Mockstream components.

MockstreamGenerator returns mockstreams

---

src/galax/utils/_jax.py

If the excluded argument was provided without starting with 0 the current code didn't fix that.

fix vectorize_method to always exclude self

---

conftest.py

Passes the `doctest.NORMALIZE_WHITESPACE` int to the Sybil parser.

ENH: normalize whitespace in doctests

---

src/galax/integrate/_builtin.py
tests/unit/potential/test_base.py

A mistake in the `DiffraxSaveAt` argument.

Fix return end time twice in orbit integration

---

src/galax/dynamics/mockstream/_mockstream_generator.py
src/galax/integrate/_base.py
src/galax/integrate/_builtin.py
src/galax/potential/_potential/base.py
tests/unit/potential/test_base.py

This is a preparatory PR for the parse_time_spec PR where we can establish a more user-friendly API. This PR just reduces some of the clutter.

Simplify time api

---

src/galax/potential/_potential/builtin.py

Sort the contents for easier maintenance.

sort the potentials

---

src/galax/dynamics/mockstream/_mockstream_generator.py
src/galax/integrate/_base.py
src/galax/integrate/_builtin.py
src/galax/potential/_potential/base.py

`Integrator.run` -> `Integrator.__call__` means that we can build a Protocol outside of the `abstract-final` Integrator hierarchy that describes an arbitrary, e.g. user-defined, integrator. 
Currently this is still limited to `dataclasses.dataclass` objects (see `AbstractPotential.integrate_orbit`), but it would be good to relax that limitation so that in the future even a function object could be used as an integrator.

Change Integrator.run to call

---

src/galax/potential/_potential/base.py

Use the private functions to avoid a lot of intermediate functions.

fix use of `acceleration` helper

---

tests/unit/dynamics/mockstream/test_mockstreamgenerator.py

Not sure this class-based approach is the best in this scenario.

Test mockstream generator

---

.pre-commit-config.yaml
src/galax/potential/_potential/__init__.py
src/galax/potential/_potential/io/__init__.py
src/galax/potential/_potential/io/gala.py
src/galax/potential/_potential/io/gala_noop.py
src/galax/potential/_potential/param/core.py
tests/smoke/potential/test_package.py
tests/unit/potential/builtin/test_nfw.py
tests/unit/potential/builtin/test_null.py
tests/unit/potential/io/gala_helper.py
tests/unit/potential/io/test_gala.py
tests/unit/potential/test_base.py

Support for UnitSystem and most potentials.
This is the simple and verbose solution.
A fair number of the conversions can be abstracted over when `galax.AbstractPotential` gets a `.parameters` attribute.
But more generally I think this interoperability should be moved to a separate package and registered in using entry points.
I'd also like to add a `to/from_format` descriptor object to `galax.AbstractPotential`, like is on `astropy.Cosmology` for a very general convenience layer for object conversion.

gala -> galax conversion

---

src/galax/potential/_potential/base.py
src/galax/potential/_potential/io/gala.py
src/galax/potential/_potential/param/attr.py
src/galax/potential/_potential/param/core.py
src/galax/potential/_potential/param/field.py
src/galax/potential/_potential/param/utils.py
tests/unit/potential/io/gala_helper.py

Modeled after `astropy.cosmology`. This attribute is computed for each subclass. When called from the class it returns a dict with ParameterField values. When called from an instance it returns a dict with the parameter values.

Potential parameters attribute

---

.pre-commit-config.yaml
pyproject.toml
src/galax/__init__.py
src/galax/__init__.pyi
tests/smoke/test_package.py

Adopt lazy loading.
Introduces a new dependency, but it is managed by `scientific-python`. Should decrease package import time.

Lazy loader

---

src/galax/dynamics/_dynamics/mockstream/mockstream_generator.py
src/galax/integrate/__init__.py
src/galax/integrate/_api.py
src/galax/integrate/_base.py
src/galax/integrate/_builtin.py
src/galax/potential/_potential/base.py
src/galax/typing.py
tests/smoke/integrate/test_package.py

Signed-off-by: nstarman <nstarman@users.noreply.github.com>

refactor: split integrator into separate module

---

src/galax/coordinates/_warnings.py
src/galax/dynamics/_dynamics/orbit.py
src/galax/potential/_potential/base.py

PhaseSpacePosition has a time attribute. `compute_orbit` now understands that the orbit should be integrated from that time.
This is a major conceptual difference from `gala`. In `galax` the time argument in the orbit integration isn't for taking time-steps in the integrator but for the return times of the orbit (the integrator is free to do it's own thing or be set by integrator-specific arguments). Since PSP has a time, we are always integrating from the PSP, returning the Orbit at the return times.
E.g. evaluating orbits for 2 time arrays:
``t1 = np.linspace(0, 10, 100) * u.Myr``
``t2 = np.linspace(-2, 10, 100) * u.Myr``
Here's `gala` `integrate_orbit`:
The PSP is taken to be at ``t1[0]`` or ``t2[0]`` so both orbits start from the same position, regardless of the difference in time. …

Orbit integration with a PSP

---

src/galax/dynamics/_dynamics/mockstream/mockstream_generator.py
src/galax/dynamics/_dynamics/mockstream/utils.py
src/galax/dynamics/_dynamics/orbit.py
src/galax/potential/_potential/base.py

This PR enables MockStreamGenerator to accept a PSP. Using a conditional time reversal and `evaluate_orbit` this also enables the auto back-integration of the progenitor, like in `gala`.

MockStream understands PSP

---

.pre-commit-config.yaml
src/galax/potential/_potential/param/field.py
src/galax/utils/dataclasses.py

It's probably worth trying to upstream this into `equinox`.
Much of this functionality is because `equinox` differs from `dataclass` wrt its treatment of `__init__`.

feat: custom dataclass transformer

---

.pre-commit-config.yaml
src/galax/__init__.py
src/galax/coordinates/__init__.py
src/galax/coordinates/__init__.pyi
src/galax/coordinates/_pspt.py
src/galax/dynamics/__init__.py
src/galax/dynamics/__init__.pyi
src/galax/potential/__init__.py
src/galax/potential/__init__.pyi
src/galax/potential/_potential/__init__.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/composite.py
src/galax/potential/_potential/param/__init__.py
src/galax/setup_package.py
tests/smoke/potential/test_package.py
tests/smoke/test_package.py

This follows the normal usage of `galax`, e.g. `import galax.dynamics as gd`.
The  current format destroys the lazy import right away.
Unfortunately https://github.com/scientific-python/lazy_loader/issues/94 means we can't do star imports in the stub files. When that's resolved everything will be a lot simpler.

refactor: use lazy_loader with subpackages

---

docs/getting_started.rst
src/galax/dynamics/_dynamics/mockstream/mockstream_generator.py
tests/unit/dynamics/mockstream/test_mockstreamgenerator.py
tests/unit/potential/test_base.py

a la `gala`.
@adrn. Do we want to keep this returning an `orbit`?

feat: return PSP, not full orbit

---

src/galax/coordinates/_psp/base.py
src/galax/coordinates/_psp/pspt.py
tests/unit/coordinates/psp/test_pspt.py

Hook PSP into the `represent_as` method for vectors

feat(PSP): represent_as method

---

src/galax/coordinates/operators/base.py
src/galax/coordinates/operators/galilean.py
src/galax/dynamics/_dynamics/mockstream/_moving.py
src/galax/potential/__init__.pyi
src/galax/potential/_potential/base.py
src/galax/potential/_potential/builtin.py
src/galax/potential/_potential/composite.py
src/galax/potential/_potential/core.py
src/galax/potential/_potential/frame.py
tests/smoke/potential/test_package.py
tests/unit/potential/builtin/test_nfw.py
tests/unit/potential/test_base.py
tests/unit/potential/test_core.py

This PR introduces / will introduce 2 concepts:
1. Operators for frame transformations: e.g. translations, rotations, boosts.
- These have both active vs passive / apply vs unapply modes.
- A set of operations can be piped together into a Sequence
- An astropy reference frame transformation is an operator sequence with particular values! I'm not sure if it will make it into this PR, but we will have an import/export option from/to Astropy CoordinateFrame objects.
2. `PotentialFrame` class that allows a a potential to be expressed in a frame relative to the simulation frame, e.g. translated to have a potential not centered at the origin. The `PotentialFrame` class knows how to "boost" coordinates into the correct frame, then evaluate the potential in that frame.

Reference Frame Transformation Operators

---

src/galax/coordinates/operators/__init__.py
src/galax/coordinates/operators/galilean.py
src/galax/coordinates/operators/rotating.py
src/galax/potential/_potential/frame.py
tests/unit/potential/test_frame.py

Now any potential can have constant rotation about z axis. Combined with a GalileanRotation operator this allows for rotation about any axes. In the docstring I do this + a time-dependent mass.
This means we can get rid of the Omega parameter in the `galax.potential.BarPotential` and just mention it in the docstring for how to get the bar rotating. Or we can leave it. Either or.
For more general rotations we need to choose whether we want to use intrinsic or extrinsic rotation, what order, etc.
Alternatively, we could forego all this subtlety by using the axis-angle formalism. Thoughts? 
Edit: IMO quaternions are the best way to do this. Very efficient. I'll change this class to `ConstrantRotationZ` that just has `Omega_z` and makes life easy for the common case. We can do general …

feat: ConstantRotationZOperator for solid-body rotation

---

src/galax/dynamics/_dynamics/integrate/_api.py
src/galax/dynamics/_dynamics/integrate/_base.py
src/galax/dynamics/_dynamics/integrate/_builtin.py
src/galax/dynamics/_dynamics/integrate/_funcs.py
src/galax/potential/_potential/base.py

Orbit interpolation!
@jnibauer, you can use this to model InterpolatedMockStream. That will be really awesome to have!

feat: Orbit interpolation

---

src/galax/potential/__init__.pyi
src/galax/potential/_potential/builtin/builtin.py
src/galax/potential/_potential/builtin/nfw.py
tests/unit/potential/builtin/test_triaxialnfw.py

Triaxial-in-the-density NFW potential, of the same type as https://docs.galpy.org/en/latest/reference/potentialtriaxialnfw.html.
The formalism is from 
```
@BOOK{1969efe..book.....C,
author = {{Chandrasekhar}, Subrahmanyan},
title = "{Ellipsoidal figures of equilibrium}",
year = 1969,
adsurl = {https://ui.adsabs.harvard.edu/abs/1969efe..book.....C},
adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
@ARTICLE{1996ApJ...460..136M,
author = {{Merritt}, David and {Fridman}, Tema},
title = "{Triaxial Galaxies with Cusps}",
journal = {\apj},
keywords = {CELESTIAL MECHANICS, STELLAR DYNAMICS, GALAXIES: KINEMATICS AND DYNAMICS, METHODS: NUMERICAL, Astrophysics},
year = 1996,
month = mar,
volume = {460},
pages = {136},
doi = {10.1086/176957},
archivePrefix = {arXiv},
eprint = …
```

feat: Triaxial (density) NFW potentials

---

src/galax/setup_package.py

Faster.
It can be enabled by setting the environment variable.

feat: runtime tyecheck off by default

---

src/galax/potential/_potential/base.py
src/galax/potential/_potential/funcs.py
src/galax/potential/_potential/utils.py
src/galax/utils/_optional_deps.py

I noticed that a lot of the implementations were the same. Rather than providing specific dispatches for every type, it's much more convenient to defer to the contained conversion functions.

refactor: cleanup funcs

---

pyproject.toml
src/galax/_interop/galax_interop_gala/potential.py
src/galax/potential/__init__.py
src/galax/potential/_potential/builtin/__init__.py
src/galax/potential/_potential/builtin/multipole.py
src/galax/potential/_potential/params/core.py
tests/unit/potential/builtin/multipole/test_abstractmultipole.py
tests/unit/potential/builtin/multipole/test_innermultipole.py
tests/unit/potential/builtin/multipole/test_multipole.py
tests/unit/potential/builtin/multipole/test_outermultipole.py
tests/unit/potential/io/test_gala.py
tests/unit/potential/param/test_core.py

Multipole potentials. Inner, Outer, & Combined.
~This currently does not support time dependence on S/Tlm, but that's entirely because of the ``__check_init__``.~

feat: multipole potentials

---

src/galax/_interop/galax_interop_astropy/dynamics.py
src/galax/coordinates/_src/__init__.py
src/galax/coordinates/_src/operators/rotating.py
src/galax/coordinates/_src/psps/core.py
src/galax/coordinates/_src/psps/interp.py
src/galax/dynamics/_src/integrate/core.py
src/galax/dynamics/_src/integrate/funcs.py
src/galax/typing.py

Achieve much closer to native diffrax speeds!
Also speeds up the doc tests and simplifies the vectorization structure and the interpolation structure.
Followup:
1. What triggers the random 100s integrations? This appears to be something in diffrax / what is passed to diffrax
2. Calls to `.w(units=...)` are SLOW. Figuring out ways to work with PSPs as PyTrees instead of doing PSP -> array -> PSP through `.w()` would make this faster.
3. Point 2 may be why in `gd.evaluate_orbit` the jitted code ends up slower for > 10^6 saved times. But this should be figured out and fixed.

feat: re-vectorize

---

src/galax/coordinates/_src/psps/base.py
src/galax/dynamics/_src/integrate/funcs.py
src/galax/dynamics/_src/integrate/integrator.py
src/galax/dynamics/_src/integrate/interp.py
src/galax/dynamics/_src/integrate/type_hints.py
src/galax/potential/_src/base.py
src/galax/typing.py

This splits q,p in the integration, which makes for a better pytree and also paves the way for unitful integration, when `quaxify(diffrax.diffeqsolve)` is enabled for Quantities.

feat(dynamics): enable q,p tuple array input to integrator 

---

src/galax/_interop/galax_interop_astropy/coordinates.py
src/galax/_interop/galax_interop_astropy/dynamics.py
src/galax/coordinates/_src/ops/rotating.py
src/galax/coordinates/_src/psps/base.py
src/galax/coordinates/_src/psps/base_composite.py
src/galax/coordinates/_src/psps/base_psp.py
src/galax/coordinates/_src/psps/core.py
src/galax/coordinates/_src/psps/core_composite.py
src/galax/coordinates/_src/psps/interp.py
src/galax/coordinates/_src/psps/operator_compat.py
src/galax/coordinates/ops.py
src/galax/dynamics/_src/integrate/funcs.py
src/galax/dynamics/_src/integrate/integrator.py
src/galax/dynamics/_src/mockstream/core.py
src/galax/dynamics/_src/mockstream/df/base.py
src/galax/dynamics/_src/mockstream/mockstream_generator.py
src/galax/dynamics/_src/orbit.py
tests/unit/coordinates/psp/test_base_psp.py
tests/unit/dynamics/test_orbit.py

This PR starts the process of transitioning PSP to the coordinax.Coordinate object framework.
Two things need more work:
1. the time storage of the PSP
2. enabling frames beyond NoFrame and then registering the dispatches for frame transforms.

✨ feat(psp): make PhaseSpacePosition a coordinax.Coordinate object

---

src/galax/coordinates/__init__.py
src/galax/coordinates/_src/ops/rotating.py
src/galax/coordinates/_src/psps/__init__.py
src/galax/coordinates/_src/psps/base.py
src/galax/coordinates/_src/psps/base_composite.py
src/galax/coordinates/_src/psps/base_psp.py
src/galax/coordinates/_src/psps/core.py
src/galax/coordinates/_src/psps/core_composite.py
src/galax/coordinates/_src/psps/interp.py
src/galax/coordinates/_src/psps/operator_compat.py
src/galax/dynamics/_src/funcs.py
src/galax/dynamics/_src/integrate/integrator.py
src/galax/dynamics/_src/mockstream/core.py
src/galax/dynamics/_src/orbit.py
src/galax/potential/_src/funcs.py
src/galax/potential/_src/utils.py
tests/unit/coordinates/psp/test_base_psp.py
tests/unit/coordinates/psp/test_psp.py
tests/unit/dynamics/test_orbit.py

I don't think people are using the ABCs yet. This does not impact the user-facing class PhaseSpacePosition.

🎨 style(coordinates): rename PSP base classes

---

src/galax/dynamics/_src/fields/base.py
src/galax/dynamics/_src/fields/hamiltonian.py
src/galax/dynamics/_src/integrate/utils.py
src/galax/dynamics/_src/solve/diffeq.py
src/galax/dynamics/_src/solve/dynamics.py
src/galax/dynamics/_src/solve/utils.py
uv.lock

@jnibauer, based on our discussion of the symplectic solver structures I made this PR, which changes `terms` from a `property` to a method that dispatches on the solver type. Now calling `terms(solver)` will e.g. return an `ODETerm(jit(self.__call__))` for Dopri8 but `(ODETerm(jit(self._call_q)), ODETerm(jit(self._call_p)))` for the symplectic solver. With this pattern it's easy for the same field type, e.g. HamiltonianField to support any required terms structure for any solver.
Closes #534

✨ feat(dynamics): term selection is now solver dependent

---

src/galax/dynamics/_src/fields/__init__.py
src/galax/dynamics/_src/fields/nbody.py
src/galax/dynamics/fields.py
uv.lock

N-Bodies!
This is better than #419 
A good followup would be to figure out how to separate the external potential from the n-body stuff and combine 2 Field objects.
Example:
```python
q = u.Quantity([[-1, 0, 0], [1, 0, 0]], "AU") / 2
p = u.Quantity([[0, -1, 0], [0, 1, 0]], "km/s") * 25
solver = gd.integrate.DynamicsSolver()
field = gd.fields.NBodyField(
masses=u.Quantity([1, 1], "Msun"),
eps=u.Quantity(1e-4, "AU"),
external_potential=gp.NullPotential(units="solarsystem"),
)
t0, t1 = u.Quantity(0, "yr"), u.Quantity(2, "yr")
soln = solver.solve(field, (q, p), t0, t1, saveat=jnp.linspace(t0, t1, 10_00))
```
```python
plt.plot(soln.ys[0][:, 0, 0], soln.ys[0][:, 0, 1])
plt.plot(soln.ys[0][:, 1, 0], soln.ys[0][:, 1, 1])
plt.show()
```

✨ feat(dynamics): nbody field

---

src/galax/dynamics/_src/integrate/funcs.py
src/galax/dynamics/_src/integrate/integrator.py
src/galax/dynamics/_src/integrate/interp.py

Almost have the `Integrator` as a lightweight wrapper around `DynamicsSolver` that just returns a `PhaseSpacePosition` instead of a `diffrax.Solution` object. Then we can switch `evaluate_orbit` to using `DynamicsSolver`, and move `Integrator` into a gala compatibility section.

💥 boom(dynamics): change integrators kwarg "interpolated" to "dense"

---

docs/getting_started.rst
src/galax/_interop/galax_interop_gala/potential.py
src/galax/potential/_src/base_multi.py
src/galax/potential/_src/base_single.py
src/galax/potential/_src/builtin/special.py
src/galax/potential/_src/composite.py
src/galax/potential/_src/params/attr.py
tests/unit/potential/builtin/special/test_bovymwpotential2014.py
tests/unit/potential/builtin/special/test_composite.py
tests/unit/potential/builtin/special/test_lm10.py
tests/unit/potential/builtin/special/test_milkywaypotential.py
tests/unit/potential/builtin/special/test_milkywaypotential2022.py

Splitting how composite potentials work.
They all still have dict methods and should work the same, but now the special potentials are built around a dataclass structure. It's much cleaner and more introspectable.
The general `CompositePotential` remains the same.

✨ feat(potential): refactor special composite potentials

---

src/galax/dynamics/__init__.py
src/galax/dynamics/_src/cluster/__init__.py
src/galax/dynamics/_src/cluster/events.py
src/galax/dynamics/_src/cluster/fields.py
src/galax/dynamics/_src/cluster/solver.py
src/galax/dynamics/_src/fields.py
src/galax/dynamics/cluster.py
tests/smoke/dynamics/test_package.py

Definitely not done. In particular, the mass fields don't yet have the cluster's orbit.

✨ feat(dynamics): cluster mass solver

---

src/galax/_interop/galax_interop_astropy/__init__.py
src/galax/_interop/galax_interop_astropy/potential.py
src/galax/_interop/galax_interop_astropy/unxt.py
src/galax/potential/_src/base.py
src/galax/potential/_src/base_multi.py
src/galax/potential/_src/builtin/bars.py
src/galax/potential/_src/builtin/disks.py
src/galax/potential/_src/builtin/example.py
src/galax/potential/_src/builtin/flattened.py
src/galax/potential/_src/builtin/logarithmic.py
src/galax/potential/_src/builtin/multipole.py
src/galax/potential/_src/builtin/nfw.py
src/galax/potential/_src/builtin/null.py
src/galax/potential/_src/builtin/special.py
src/galax/potential/_src/builtin/spherical.py
src/galax/potential/_src/params/core.py
src/galax/potential/_src/params/field.py
src/galax/potential/_src/register_funcs.py
src/galax/potential/_src/utils.py
src/galax/potential/_src/xfm/triaxial.py
src/galax/potential/_src/xfm/xop.py
src/galax/typing.py
src/galax/utils/_unxt.py
tests/unit/potential/builtin/nfw/test_triaxialnfw.py
tests/unit/potential/test_base.py
tests/unit/potential/test_core.py

```python
pot = gp.BurkertPotential(m=1e12, r_s=2, units="galactic")
w = gc.PhaseSpaceCoordinate(
q=u.Quantity([1, 2, 3], "kpc"),
p=u.Quantity([4, 5, 6], "km/s"),
t=u.Quantity(0, "Gyr"),
)
@jax.jit
def func(*args):
return pot._potential(*args)
print("HERE", jax.block_until_ready(func(xyz, t)))  # trigger jit
%timeit jax.block_until_ready(func(xyz, t))
```
@jnibauer The time comes out almost identical to a hand implementation of the Burkert potential! 
This shows the path for performance optimization: Arrays in -> Arrays out. Q & higher in -> Q & higher out.

♻️ refactor(potential): _potential works on arrays directly

---

src/galax/potential/_src/builtin/multipole.py
src/galax/potential/_src/builtin/nfw.py
tests/unit/potential/builtin/multipole/test_abstractmultipole.py
tests/unit/potential/builtin/multipole/test_innermultipole.py
tests/unit/potential/builtin/multipole/test_multipole.py
tests/unit/potential/builtin/multipole/test_outermultipole.py
tests/unit/potential/test_base.py
tests/unit/potential/test_core.py

This is a bug that Katie and I stumbled on. Inside of a JITted function, we create a potential instance. We tried using the `LeeSutoNFWPotential` but get a `TracerBoolConversionError` - I think it's related to the Python `or` in the `__check_init
__`, so I switched that out for a `jnp.logical_or`. 
I also added a test to make sure all builtin potentials are safe from this and found a few other things to fix (commit coming).

Bugfix: Use "jnp.logical_or" instead of "or" for JAX tracer support

---

README.md

Eventually we should have some developer documentation, but I thought in the short term we could at least have a small note about using `uv` to run the tests (at least to remind me 😅).

Add blurb to README about uv

---

pyproject.toml

This temporarily adds an upper bound to the coordinax version dependency because of the current incompatibility with coordinax v0.21.0.

Put upper bound on incompatible coordinax version

---

src/galax/_interop/matplotlib/orbit.py
tests/integration/matplotlib/hashes.json
tests/integration/matplotlib/test_orbit.py

This adds a dispatch for `plot_components` when no components are specified to plot all pairs of components for an orbit.
I had to change the order of arguments to squeeze `x` and `y` into the positional arguments (to dispatch over). But alternatively I could make them `str | None = None` in a dispatched `plot_components()` outer function, and implement `_plot_components_single` and `_plot_components_all` to be called within. Thoughts?

Add dispatched function to plot all components of an orbit
