GalacticDynamics/galax

pyproject.toml
src/galdynamix/dynamics/__init__.py
src/galdynamix/dynamics/mockstream/__init__.py
src/galdynamix/dynamics/mockstream/_df/__init__.py
src/galdynamix/dynamics/mockstream/_df/base.py
src/galdynamix/integrate/__init__.py
src/galdynamix/potential/__init__.py
src/galdynamix/potential/_potential/__init__.py
src/galdynamix/potential/_potential/builtin.py
src/galdynamix/potential/_potential/param/__init__.py
src/galdynamix/potential/_potential/param/field.py
src/galdynamix/utils/__init__.py

Add ruff ignores

---

pyproject.toml
src/galdynamix/potential/_potential/base.py
src/galdynamix/potential/_potential/builtin.py
src/galdynamix/potential/_potential/param/core.py
src/galdynamix/potential/_potential/param/field.py
src/galdynamix/potential/_potential/subhalo.py
src/galdynamix/units.py
src/galdynamix/utils/_jax.py
src/galdynamix/utils/dataclasses.py

Change `physical_type` to `dimensions`.

Dimensions

---

.pre-commit-config.yaml
pyproject.toml
src/galdynamix/potential/_potential/base.py
src/galdynamix/potential/_potential/composite.py
src/galdynamix/utils/_collections.py
src/galdynamix/utils/_jax.py
src/galdynamix/utils/_misc.py
src/galdynamix/utils/dataclasses.py
tests/test_package.py
tests/utils/test_collections.py
tests/utils/test_dataclasses.py
tests/utils/test_jax.py
tests/utils/test_misc.py
tests/utils/test_package.py

Misc fixes following phasespaceposition merge

---

src/galdynamix/potential/_potential/composite.py

don’t repr _G

---

src/galdynamix/dynamics/_core.py
src/galdynamix/dynamics/mockstream/_core.py
src/galdynamix/potential/_potential/base.py
src/galdynamix/typing.py
src/galdynamix/utils/_shape.py

utils for working with batches and array shapes.

Shape utils

---

src/galdynamix/potential/_potential/base.py
src/galdynamix/potential/_potential/builtin.py
src/galdynamix/potential/_potential/composite.py
src/galdynamix/potential/_potential/param/core.py
src/galdynamix/typing.py

A perpetual work in progress to get the batching correct over scalar and vector inputs.

More vectorizations

---

pyproject.toml
src/galdynamix/typing.py
src/galdynamix/utils/_shape.py

It repeated dimension 0, rather than setting it to ordinality.

fix expand_batch_dims to allow multiple dims

---

src/galdynamix/dynamics/_core.py

Angular momentum property

---

src/galdynamix/potential/_potential/base.py
src/galdynamix/potential/_potential/utils.py
src/galdynamix/utils/dataclasses.py

Equinox does converting late, after setting. It's better to convert before even setting. See relevant PIP, `attrs` library, etc.

Early convert init

---

src/galdynamix/potential/_potential/param/core.py

Signed-off-by: nstarman <nstarman@users.noreply.github.com>

Add converter for AbstractParameter unit

---

src/galax/dynamics/mockstream/_mockstream_generator.py

Pass the correct quantities to run_vmap

---

src/galax/dynamics/_core.py
src/galax/dynamics/_orbit.py
src/galax/dynamics/mockstream/_core.py
src/galax/integrate/_builtin.py
src/galax/potential/_potential/base.py
tests/unit/potential/test_base.py

Now we can integrate any shaped w0!

batch orbit integration

---

src/galax/dynamics/mockstream/_mockstream_generator.py

fix selection of integrated state

---

src/galax/dynamics/_core.py
src/galax/dynamics/mockstream/_df/base.py
src/galax/integrate/_base.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/core.py
src/galax/potential/_potential/param/core.py

High level of type strictness.

enforce strict abstract-concrete

---

src/galax/dynamics/mockstream/_mockstream_generator.py

Fixes #63.
This should mean we don't have to worry about specifying the mockstream generation method!

auto-detect backend to choose stream gen method

---

src/galax/potential/_potential/base.py

units always keyword-only

---

src/galax/potential/_potential/builtin.py
tests/unit/potential/builtin/test_common.py
tests/unit/potential/builtin/test_hernquist.py

Pot hern match gala

---

tests/unit/potential/builtin/test_bar.py
tests/unit/potential/builtin/test_hernquist.py
tests/unit/potential/builtin/test_isochrone.py
tests/unit/potential/builtin/test_miyamotonagai.py
tests/unit/potential/builtin/test_nfw.py
tests/unit/potential/builtin/test_null.py
tests/unit/potential/test_core.py

How pytest collects import tests.

prevent repeating tests from imports

---

pyproject.toml
src/galax/integrate/_builtin.py

combine as imports

---

tests/unit/potential/builtin/test_bar.py
tests/unit/potential/builtin/test_hernquist.py
tests/unit/potential/builtin/test_isochrone.py
tests/unit/potential/builtin/test_miyamotonagai.py
tests/unit/potential/builtin/test_nfw.py
tests/unit/potential/builtin/test_null.py
tests/unit/potential/test_core.py

Signed-off-by: nstarman <nstarman@users.noreply.github.com>

consolidate test_acceleration

---

pyproject.toml

The comprehensive install option.

all optional dependencies

---

src/galax/potential/_potential/__init__.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/utils.py
tests/unit/potential/test_base.py

This is the start of a framework that can handle unit-ful inputs to functions.
The larger issue is that `jax.jit` can't handle Quantity inputs. We need to make a decorator that can parse inputs before passing them to the jitted function.

Parse inputs

---

src/galax/dynamics/mockstream/_df/base.py

fix mockstream shape

---

pyproject.toml
src/galax/potential/_potential/__init__.py
src/galax/potential/_potential/composite.py
src/galax/potential/_potential/special.py
tests/smoke/potential/test_package.py
tests/unit/potential/builtin/test_mwpotential.py
tests/unit/potential/test_base.py
tests/unit/potential/test_composite.py
tests/unit/potential/test_core.py
tests/unit/potential/test_special.py

Add MilkyWayPotential

---

.pre-commit-config.yaml

Commitizen

---

docs/getting_started.rst
src/galax/dynamics/__init__.py
src/galax/dynamics/_base.py
src/galax/dynamics/_core.py
src/galax/dynamics/_orbit.py
src/galax/dynamics/mockstream/_core.py
src/galax/dynamics/mockstream/_df/base.py
src/galax/dynamics/mockstream/_df/fardal.py
src/galax/dynamics/mockstream/_mockstream_generator.py
src/galax/integrate/_base.py
src/galax/integrate/_builtin.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/io/gala.py
src/galax/typing.py
tests/smoke/dynamics/test_package.py
tests/unit/dynamics/mockstream/test_mockstreamgenerator.py
tests/unit/dynamics/test_core.py
tests/unit/potential/test_base.py
tests/unit/utils/test_dataclasses.py
tests/unit/utils/test_misc.py

PhaseSpacePosition now includes the time and cleans up the inheritance hierarchy.
The longer-term plan is to have the orbit integrator understand the time of the PSP, which is different than the return times specified in the integrator.

Refactor PhaseSpacePosition

---

src/galax/dynamics/_base.py
src/galax/dynamics/_orbit.py
src/galax/dynamics/mockstream/_core.py
src/galax/dynamics/mockstream/_df/base.py
src/galax/dynamics/mockstream/_df/fardal.py
src/galax/dynamics/mockstream/_mockstream_generator.py
src/galax/integrate/_builtin.py
src/galax/potential/_potential/param/attr.py
src/galax/potential/_potential/param/core.py
src/galax/potential/_potential/param/field.py
src/galax/units.py

chore: decorate final

---

src/galax/dynamics/_dynamics/base.py
src/galax/dynamics/_dynamics/core.py
src/galax/dynamics/_dynamics/mockstream/core.py
src/galax/dynamics/_dynamics/orbit.py
src/galax/dynamics/_dynamics/utils.py
src/galax/potential/_potential/base.py
tests/unit/dynamics/test_core.py

- Adds the attribute `ndim`, which was a missing attribute for Array-like objects.
- various fixes
- addresses issue with slicing

PSP array-like

---

src/galax/dynamics/_dynamics/orbit.py
src/galax/potential/_potential/base.py

I like the functional approach with the method on the Potential as a convenience method.

feat: add function `integrate_orbit` to dynamics module

---

src/galax/coordinates/_pspt.py
tests/unit/coordinates/test_pspt.py
tests/unit/dynamics/test_orbit.py

feat: move time to 1st column

---

src/galax/potential/_potential/param/core.py
tests/unit/potential/param/test_core.py

I think this is a good idea. But I don't take lightly adding things to the public API.

feat(param): add ParameterCallable to public API

---

src/galax/potential/_potential/builtin.py

I need to add integration tests demonstrating this. Also hopefully fixing the reversions I found to be necessary in this PR.

Blackjax Compatability

---

docs/getting_started.rst
src/galax/dynamics/_dynamics/mockstream/df/fardal.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/composite.py
src/galax/potential/_potential/utils.py
src/galax/typing.py
tests/unit/potential/builtin/test_bar.py
tests/unit/potential/builtin/test_hernquist.py
tests/unit/potential/builtin/test_isochrone.py
tests/unit/potential/builtin/test_miyamotonagai.py
tests/unit/potential/builtin/test_mwpotential.py
tests/unit/potential/builtin/test_nfw.py
tests/unit/potential/builtin/test_null.py
tests/unit/potential/io/test_gala.py
tests/unit/potential/test_base.py
tests/unit/potential/test_composite.py
tests/unit/potential/test_special.py

Quantify methods on potential

---

src/galax/potential/_potential/builtin.py
src/galax/potential/_potential/composite.py
src/galax/potential/_potential/core.py
src/galax/potential/_potential/special.py
src/galax/potential/_potential/utils.py
src/galax/units.py
tests/unit/potential/test_composite.py
tests/unit/potential/test_core.py
tests/unit/potential/test_special.py
tests/unit/potential/test_utils.py

A more useful and flexible function than the converter.

feat: unitsystem function

---

src/galax/coordinates/operators/base.py
src/galax/coordinates/operators/composite.py
src/galax/coordinates/operators/galilean.py
src/galax/coordinates/operators/identity.py

Extend `AbstractOperator.__call__` to work on PSP and PSPT.

feat: op on psp

---

src/galax/coordinates/_psp/pspt.py
src/galax/coordinates/_psp/utils.py
src/galax/dynamics/_dynamics/mockstream/core.py
src/galax/dynamics/_dynamics/mockstream/mockstream_generator.py
src/galax/dynamics/_dynamics/orbit.py
src/galax/typing.py
src/galax/utils/dataclasses.py
tests/unit/coordinates/psp/test_pspt.py
tests/unit/coordinates/psp/test_utils.py
tests/unit/dynamics/mockstream/test_mockstreamgenerator.py
tests/unit/dynamics/test_orbit.py

Currently this means time must be a Quantity.

feat: PSP time as a Quantity

---

src/galax/coordinates/operators/galilean.py
src/galax/utils/dataclasses.py

This is a single rotation, not a time-dependent rotation.

feat: galilean rotation

---

src/galax/coordinates/operators/base.py

Interpreting as a CartesianVector.

feat: apply op to Quantity

---

src/galax/potential/__init__.pyi
src/galax/potential/_potential/builtin.py
tests/unit/potential/builtin/test_common.py
tests/unit/potential/builtin/test_triaxialhernquist.py

There's something strange with the density. Who are we going to call? Maintainers!

feat: triaxial hernquist potential

---

src/galax/potential/_potential/builtin.py
src/galax/potential/_potential/param/field.py
src/galax/utils/dataclasses.py

With this parameters on potentials can have default values.

feat: parameter defaults

---

src/galax/dynamics/_dynamics/integrate/_builtin.py

Signed-off-by: nstarman <nstarman@users.noreply.github.com>

refactor: diffrax import

---

src/galax/dynamics/_dynamics/mockstream/df/fardal.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/builtin.py
src/galax/potential/_potential/composite.py
src/galax/potential/_potential/core.py
src/galax/potential/_potential/frame.py
src/galax/potential/_potential/special.py
tests/unit/potential/test_base.py
tests/unit/potential/test_core.py
tests/unit/potential/test_utils.py

This should be quaxed properly

feat: constants on potentials

---

src/galax/dynamics/_dynamics/integrate/_api.py
src/galax/dynamics/_dynamics/integrate/_base.py
src/galax/dynamics/_dynamics/integrate/_builtin.py
src/galax/dynamics/_dynamics/integrate/_funcs.py

This is only in the integrator. We need to figure out the best API for `evaluate_orbit`.

feat: integrator t0, t1, savet

---

src/galax/dynamics/_dynamics/mockstream/mockstream_generator.py

fix: mockstream where PSP.t is None

fix: mockstream where PSP.t is None

---

src/galax/dynamics/_dynamics/integrate/_builtin.py
src/galax/potential/_potential/builtin.py
src/galax/typing.py
tests/unit/dynamics/mockstream/test_mockstreamgenerator.py
tests/unit/potential/io/gala_helper.py
tests/unit/potential/io/test_gala.py

refactor: diffrax integration

---

src/galax/dynamics/_dynamics/integrate/_base.py
src/galax/dynamics/_dynamics/integrate/_builtin.py
src/galax/dynamics/_dynamics/integrate/_funcs.py
src/galax/dynamics/_dynamics/mockstream/df/_base.py
src/galax/dynamics/_dynamics/mockstream/df/_progenitor.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/builtin.py
src/galax/potential/_potential/frame.py
src/galax/potential/_potential/io/_gala.py
src/galax/potential/_potential/param/attr.py
src/galax/potential/_potential/special.py
tests/functional/test_mockstreamgenerator.py
tests/unit/coordinates/psp/test_base.py
tests/unit/potential/builtin/test_bar.py
tests/unit/potential/builtin/test_common.py
tests/unit/potential/builtin/test_hernquist.py
tests/unit/potential/builtin/test_isochrone.py
tests/unit/potential/builtin/test_kepler.py
tests/unit/potential/builtin/test_leesutotriaxialnfw.py
tests/unit/potential/builtin/test_miyamotonagai.py
tests/unit/potential/builtin/test_nfw.py
tests/unit/potential/builtin/test_triaxialhernquist.py
tests/unit/potential/io/gala_helper.py
tests/unit/potential/test_base.py
tests/unit/potential/test_composite.py
tests/unit/potential/test_core.py
tests/unit/potential/test_frame.py
tests/unit/potential/test_special.py

This is the one parameter name convention we agreed on. Shape parameters and such will be done in a followup PR.

feat: rename select m to m_tot

---

src/galax/coordinates/__init__.py
src/galax/coordinates/_compat.py
src/galax/dynamics/__init__.py
src/galax/dynamics/_compat.py

Not tested because gala isn't in the test matrix. Should do that...

feat: psp gala compat

---

src/galax/potential/__init__.pyi
src/galax/potential/_potential/builtin.py
src/galax/potential/_potential/io/_gala.py
src/galax/utils/_optional_deps.py
tests/unit/potential/builtin/test_powerlawcutoff.py
tests/unit/potential/io/gala_helper.py

Powerlaw + cutoff potential. Necessary for Bovy MWPot 2014.
Unfortunately I don't know how to get Gala + GSL in the CI, so this is only compared to gala locally.
See #278

feat: powerlawcutoff potential

---

src/galax/potential/__init__.pyi
src/galax/potential/_potential/base.py
src/galax/potential/_potential/builtin/__init__.py
src/galax/potential/_potential/builtin/builtin.py
src/galax/potential/_potential/builtin/nfw.py
src/galax/potential/_potential/special.py
src/galax/typing.py
tests/unit/potential/builtin/test_common.py
tests/unit/potential/builtin/test_leesutotriaxialnfw.py
tests/unit/potential/builtin/test_nfw.py
tests/unit/potential/builtin/test_triaxialhernquist.py
tests/unit/potential/builtin/test_vogelsberger08nfw.py

From https://doi.org/10.1111/j.1365-2966.2007.12746.x

feat: Vogelsberger’08 NFW

---

src/galax/utils/_optional_deps.py

Until https://github.com/adrn/gala/issues/372

build: opt dep check

---

src/galax/coordinates/_compat.py
src/galax/coordinates/_psp/utils.py
src/galax/dynamics/_dynamics/base.py
tests/unit/coordinates/psp/test_utils.py

Add dispatches to the PSP constructor for astropy coordinate objects.

feat(psp): constructor from astropy coordinates

---

src/galax/dynamics/_dynamics/integrate/_base.py
src/galax/dynamics/_dynamics/integrate/_builtin.py
src/galax/potential/_potential/builtin/builtin.py
src/galax/potential/_potential/builtin/special.py
src/galax/potential/_potential/frame.py
src/galax/potential/_potential/io/_gala.py
tests/unit/potential/builtin/misc/test_hernquist.py
tests/unit/potential/builtin/misc/test_triaxialhernquist.py
tests/unit/potential/io/gala_helper.py

Standardising the scale radii. We decided on r_s.

feat(pot): rename parameter c to r_s

---

src/galax/potential/__init__.pyi
src/galax/potential/_potential/param/core.py

A simple demonstration of time-dependent parameters

feat: LinearParameter

---

src/galax/dynamics/_dynamics/mockstream/df/_base.py
src/galax/dynamics/_dynamics/mockstream/mockstream_generator.py

Rather than a tuple of the arms.

feat: df sample returns full mockstream

---

docs/getting_started.rst
src/galax/coordinates/_compat.py
src/galax/coordinates/_psp/base.py
src/galax/coordinates/_psp/base_composite.py
src/galax/coordinates/_psp/base_psp.py
src/galax/coordinates/_psp/compat_apy.py
src/galax/coordinates/_psp/core.py
src/galax/coordinates/_psp/interp.py
src/galax/coordinates/_psp/operator_compat.py
src/galax/coordinates/_psp/utils.py
src/galax/coordinates/operators/_rotating.py
src/galax/dynamics/_dynamics/base.py
src/galax/dynamics/_dynamics/integrate/_base.py
src/galax/dynamics/_dynamics/integrate/_builtin.py
src/galax/dynamics/_dynamics/integrate/_funcs.py
src/galax/dynamics/_dynamics/mockstream/core.py
src/galax/dynamics/_dynamics/mockstream/df/_base.py
src/galax/dynamics/_dynamics/orbit.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/frame.py
src/galax/potential/_potential/funcs.py
src/galax/potential/_potential/utils.py
tests/unit/coordinates/psp/test_base_psp.py
tests/unit/potential/io/test_gala.py

See https://github.com/GalacticDynamics/coordinax/pull/115

feat: use new coordinax names

---

README.md

@MichaelAnckaert, do you have any suggestions / requests for the ReadMe? We're happy to shout out in another way.

docs: add contributors to readme

---

src/galax/dynamics/_dynamics/mockstream/df/_base.py
src/galax/dynamics/_dynamics/mockstream/df/_fardal.py
src/galax/dynamics/_dynamics/mockstream/mockstream_generator.py
tests/functional/test_mockstreamgenerator.py
tests/unit/dynamics/mockstream/test_mockstreamgenerator.py

feat: use jax’s newer prng

---

src/galax/dynamics/_dynamics/mockstream/df/_base.py
src/galax/dynamics/_dynamics/mockstream/df/_fardal.py
src/galax/dynamics/_dynamics/mockstream/mockstream_generator.py

This PR acknowledges that both the leading and trailing arms are always simulated. Also the DF is cleaned up a lot.

Mockgen lead trail

---

src/galax/coordinates/_compat.py
src/galax/coordinates/_psp/base.py
src/galax/coordinates/_psp/base_composite.py
src/galax/coordinates/_psp/core.py
src/galax/coordinates/_psp/interp.py
src/galax/dynamics/_dynamics/integrate/_base.py
src/galax/dynamics/_dynamics/mockstream/df/_base.py
src/galax/dynamics/_dynamics/mockstream/df/_fardal15.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/funcs.py
src/galax/typing.py
tests/functional/test_mockstreamgenerator.py

Get the integrator working with Composite PSPs

Refactor integrator

---

src/galax/dynamics/_dynamics/integrate/_base.py
src/galax/dynamics/_dynamics/integrate/_builtin.py
src/galax/dynamics/_dynamics/integrate/_funcs.py
src/galax/potential/_potential/base.py

Fix regression introduced in #349

Fix dynamics eq

---

conftest.py
src/galax/coordinates/_compat.py
src/galax/dynamics/_compat.py
src/galax/potential/_potential/io/_gala.py

This avoids `pytest` in the main code.

test: change test collection

---

src/galax/potential/_potential/base.py

feat: start as_interop

---

pyproject.toml
src/galax/coordinates/_psp/base.py
src/galax/coordinates/_psp/base_composite.py
src/galax/dynamics/_dynamics/integrate/api.py
src/galax/utils/dataclasses.py

This moves some utils into a separate package.

build: use dataclasstools

---

.github/workflows/ci.yml
pyproject.toml

bump: gala

---

pyproject.toml
src/galax/coordinates/_psp/base.py
src/galax/dynamics/__init__.py
src/galax/dynamics/_dynamics/funcs.py
src/galax/dynamics/_dynamics/mockstream/df/chen24.py
src/galax/dynamics/_dynamics/mockstream/df/fardal15.py
tests/smoke/dynamics/test_package.py

feat: more dynamics funcs

---

src/galax/_interop/galax_interop_astropy/dynamics.py
src/galax/coordinates/_psp/base.py
src/galax/dynamics/_dynamics/base.py
src/galax/potential/_potential/base.py
src/galax/potential/_potential/builtin/bars.py
src/galax/potential/_potential/builtin/builtin.py
src/galax/potential/_potential/builtin/logarithmic.py
src/galax/potential/_potential/builtin/nfw.py
src/galax/potential/_potential/composite.py
src/galax/potential/_potential/funcs.py
src/galax/potential/_potential/params/core.py
tests/unit/potential/test_base.py
tests/unit/potential/test_core.py

Targeting functions with few lines.

refactor: inline some jits

---

src/galax/potential/_potential/params/core.py
src/galax/potential/_potential/params/field.py
src/galax/utils/dataclasses.py
tests/unit/utils/test_dataclasses.py

Avoids lambda functions.
More type friendly.
Better introspection.

refactor: improve converters

---

src/galax/dynamics/_src/integrate/__init__.py
src/galax/dynamics/_src/integrate/core.py
src/galax/dynamics/_src/integrate/type_hints.py
src/galax/dynamics/_src/orbit.py
src/galax/dynamics/integrate.py
src/galax/potential/_src/base.py
tests/smoke/dynamics/integrate/test_package.py

Prelude to speeding up the vectorization.

Refactor: clean up the Integrator

---

pyproject.toml
src/galax/dynamics/_src/integrate/core.py

knock-on effects of implementing `__len__`.

fix: vectorizing PSP return

---

src/galax/coordinates/_src/psps/base.py
src/galax/dynamics/_src/integrate/core.py
src/galax/dynamics/_src/integrate/funcs.py
src/galax/dynamics/_src/orbit.py

significantly simplifying the logic and enabling single-time evaluations!
Also faster.

refactor: evaluate_orbit

---

docs/getting_started.rst
noxfile.py
src/galax/_interop/galax_interop_gala/potential.py
src/galax/_interop/galax_interop_galpy/potential.py
src/galax/potential/_src/builtin/builtin.py
src/galax/potential/_src/composite.py
src/galax/potential/_src/params/attr.py
src/galax/potential/_src/params/core.py
tests/unit/potential/param/test_core.py

refactor: constant parameter

---

.github/workflows/ci.yml
pyproject.toml

build: enable py3.13

---

src/galax/dynamics/_src/solve/dynamicsolver.py

This also reverses the argument order to put w0 first.

✨ feat(dynamics): add DynamicsSolver dispatches

---

pyproject.toml
src/galax/_interop/galax_interop_gala/coordinates.py
src/galax/_interop/galax_interop_gala/potential.py
src/galax/_interop/galax_interop_galpy/potential.py
src/galax/dynamics/_src/fields/base.py
src/galax/dynamics/_src/fields/hamiltonian.py
src/galax/dynamics/_src/integrate/integrator.py
src/galax/dynamics/_src/integrate/interp.py
src/galax/dynamics/_src/integrate/utils.py
src/galax/dynamics/_src/solve/diffeq.py
src/galax/dynamics/_src/solve/dynamics.py
src/galax/dynamics/_src/solve/utils.py
uv.lock

🎨 style(imports): standardize imports

---

src/galax/coordinates/__init__.py
src/galax/coordinates/_src/psps/__init__.py
src/galax/coordinates/_src/psps/interp.py
src/galax/dynamics/_src/integrate/__init__.py
src/galax/dynamics/_src/integrate/integrator.py
src/galax/dynamics/_src/integrate/interp.py
src/galax/dynamics/_src/integrate/interp_psp.py
src/galax/dynamics/integrate.py
tests/smoke/dynamics/integrate/test_package.py

It's the only place it's used.

🎨 style(coordinates): move some PSP interpolation to dynamics

---

src/galax/_interop/galax_interop_astropy/dynamics.py
src/galax/dynamics/__init__.py
src/galax/dynamics/_src/dynamics/field_hamiltonian.py
src/galax/dynamics/_src/dynamics/field_nbody.py
src/galax/dynamics/_src/dynamics/register_gc.py
src/galax/dynamics/_src/dynamics/solver.py
src/galax/dynamics/_src/fields.py
src/galax/dynamics/_src/solver.py
src/galax/dynamics/integrate.py
src/galax/dynamics/solve.py
tests/smoke/dynamics/integrate/test_package.py
tests/smoke/dynamics/test_package.py

Also, moving some stuff out of the integrate namespace

✨ feat(dynamics): add solve namespace

---

src/galax/dynamics/_src/cluster/solver.py
src/galax/dynamics/_src/dynamics/compat.py
src/galax/dynamics/_src/dynamics/solver.py
src/galax/dynamics/_src/solver.py
src/galax/dynamics/solve.py

Still needs to be code cleanup, particularly to consolidate the `solve()` code into a `.init()`, `._run` (which returns a Solution object). Now `init()` can take care of all the various ways to initialize the solve! And the step, run, solve methods can be relatively simple.

DynamicsSolver init, step, run 

---

src/galax/dynamics/__init__.py
src/galax/dynamics/_src/legacy/funcs.py
src/galax/dynamics/_src/mockstream/df/base.py
src/galax/dynamics/_src/orbit/__init__.py
src/galax/dynamics/_src/orbit/compute.py
src/galax/dynamics/solve.py
src/galax/potential/_src/base.py
tests/smoke/dynamics/test_package.py

Starting the transition from `evaluate_orbit`.

✨ feat(dynamics): compute_orbit

---

src/galax/coordinates/_src/base.py
src/galax/coordinates/_src/pscs/base.py
src/galax/coordinates/_src/pscs/base_composite.py
src/galax/coordinates/_src/pscs/single.py
src/galax/coordinates/_src/psps/core.py
src/galax/coordinates/_src/utils.py
src/galax/dynamics/_src/legacy/interp_psp.py
src/galax/dynamics/_src/mockstream/arm.py
src/galax/dynamics/_src/orbit/base.py

Room for further simplification by moving some of the logic up into coordinax.

♻️ refactor(coordinates): improve getitem with pytree ops

---

src/galax/dynamics/_src/dynamics/field_hamiltonian.py
src/galax/dynamics/_src/fields.py

Eventually it would be nice to use a MultiTerm to centralize how `terms` is built.

✨ feat(dynamics): symplectic terms for hamiltonianfield

---

pyproject.toml
src/galax/potential/__init__.py
src/galax/potential/_src/__init__.py
src/galax/potential/_src/base_multi.py
src/galax/potential/_src/plot.py
src/galax/potential/_src/xfm/__init__.py
src/galax/potential/_src/xfm/translate.py
src/galax/potential/params.py
tests/smoke/potential/test_package.py
uv.lock

Adding `interpax` as a dependency. Maybe later we want to separate that dependence into an extension?

✨ feat(potential): convenience class for time-dep translations

---

src/galax/coordinates/_src/pscs/base.py

Do we even need the `wt` method? Or can we merge it into `w` so that it's a 6-vector for PhaseSpacePosition and a 7-vector for PhaseSpaceCoordinate?

📝 docs(coordinates): wt docs

---

README.md
docs/getting_started.rst
src/galax/_interop/galax_interop_astropy/dynamics.py
src/galax/_interop/matplotlib/orbit.py
src/galax/dynamics/_src/cluster/fields.py
src/galax/dynamics/_src/cluster/sample.py
src/galax/dynamics/_src/legacy/funcs.py
src/galax/dynamics/_src/orbit/__init__.py
src/galax/dynamics/_src/orbit/base.py
src/galax/dynamics/_src/orbit/compute.py
src/galax/dynamics/_src/orbit/orbit.py
src/galax/dynamics/_src/orbit/register_dfx.py
tests/unit/dynamics/test_orbit.py

Simpler. Better pytree structure. Faster.

♻️ refactor(dynamics): orbits do not store the potential

---

pyproject.toml
src/galax/dynamics/__init__.py
src/galax/dynamics/_src/custom_types.py
src/galax/dynamics/_src/experimental/__init__.py
src/galax/dynamics/_src/experimental/integrate.py
src/galax/dynamics/_src/experimental/stream.py
src/galax/dynamics/_src/experimental/stream_dev.py
src/galax/utils/loop_strategies.py
uv.lock

Faster integrator and stream generation.
Going to refactor this and the existing framework to make a [easier], better, faster, stronger framework.

✨ feat(dynamics): experimental module

---

src/galax/dynamics/_src/experimental/stream.py

Dense (interpolated) solutions to streams.
Incorporated directly into the scan/vmap dispatches.
No slowdown, just another jit compile if the value changes. Same as if they were separate functions.

✨ feat(dynamics): dense streams

---

src/galax/dynamics/_src/experimental/stream.py
tests/benchmark/test_experimental.py

✨ feat(dynamics): StreamSimulator

---

CONVENTIONS.md
src/galax/potential/__init__.py
src/galax/potential/_src/xfm/__init__.py
src/galax/potential/_src/xfm/flattened.py
tests/smoke/potential/test_package.py

Parameter name up for discussion...

Add a Flattened analog to TriaxialInThePotential
